/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type SearchWithDatePeriod struct {

	// 开始日期时间戳
	StartDate float32 `json:"startDate,omitempty"`

	// 结束日期时间戳
	EndDate float32 `json:"endDate,omitempty"`
}
