/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type AircraftExperiencesOverrideRowUpsert struct {

	// 员工号
	StaffID string `json:"staffID,omitempty"`

	AircraftExperiences []AircraftType `json:"AircraftExperiences,omitempty"`
}
