/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type CheckRideType string

// List of CheckRideType
const (
	F1_ CheckRideType = "F1 初始改装/转机型"
	F2 CheckRideType = "F2 航线检查"
	F22 CheckRideType = "F2 模拟机检查"
	F2B CheckRideType = "F2b 航线检查"
	F3 CheckRideType = "F3 模拟机检查"
	F3B CheckRideType = "F3b 航线检查"
	F3B2 CheckRideType = "F3b 模拟机检查"
	F3B3 CheckRideType = "F3b 航线检查"
	F4 CheckRideType = "F4 模拟机检查"
	F42 CheckRideType = "F4 航线检查"
	F5 CheckRideType = "F5 口试"
	F52 CheckRideType = "F5 模拟机评估"
	F5_1 CheckRideType = "F5 航线检查1"
	F5_2 CheckRideType = "F5 航线检查2"
	F5_3 CheckRideType = "F5 航线检查3"
	F5_4 CheckRideType = "F5 航线检查4"
	F53 CheckRideType = "F5 局方检查"
	M CheckRideType = "M 本场"
	J CheckRideType = "J 模拟机"
	J2 CheckRideType = "J 航线检查"
	A1 CheckRideType = "A1 航线检查"
	A2 CheckRideType = "A2 航线检查"
	A2B CheckRideType = "A2b 航线检查"
	TA CheckRideType = "Ta 本场"
	TA2 CheckRideType = "Ta 模拟机评估"
	TA3 CheckRideType = "Ta 模拟机检查"
	TB CheckRideType = "Tb 模拟机评估"
	TB2 CheckRideType = "Tb 模拟机检查"
)
