/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type CheckRideType string

// List of CheckRideType
const (
	F1_SIM_ CheckRideType = "F1_Sim 初始改装/转机型"
	F2_FLIGHT CheckRideType = "F2_Flight 航线检查"
	F2_SIM CheckRideType = "F2_Sim 模拟机检查"
	F2B_FLIGHT CheckRideType = "F2b_Flight 航线检查"
	F3_SIM CheckRideType = "F3_Sim 模拟机检查"
	F3B_FLIGHT CheckRideType = "F3b_Flight 航线检查"
	F3B_SIM CheckRideType = "F3b_Sim 模拟机检查"
	F3B_FLIGHT2 CheckRideType = "F3b_Flight 航线检查"
	F4_SIM CheckRideType = "F4_Sim 模拟机检查"
	F4_FLIGHT CheckRideType = "F4_Flight 航线检查"
	F5_ORAL CheckRideType = "F5_Oral 口试"
	F5_SIM_EVAL CheckRideType = "F5_SimEval 模拟机评估"
	F5_FLIGHT1_1 CheckRideType = "F5_Flight1 航线检查1"
	F5_FLIGHT2_2 CheckRideType = "F5_Flight2 航线检查2"
	F5_FLIGHT3_3 CheckRideType = "F5_Flight3 航线检查3"
	F5_FLIGHT4_4 CheckRideType = "F5_Flight4 航线检查4"
	F5_SIM CheckRideType = "F5_Sim 局方检查"
	M_TRAFFIC_PATTERN CheckRideType = "M_TrafficPattern 本场"
	J_SIM CheckRideType = "J_Sim 模拟机"
	J_FLIGHT CheckRideType = "J_Flight 航线检查"
	A1_FLIGHT CheckRideType = "A1_Flight 航线检查"
	A2_FLIGHT CheckRideType = "A2_Flight 航线检查"
	A2B_FLIGHT CheckRideType = "A2b_Flight 航线检查"
	TA_TRAFFIC_PATTERN CheckRideType = "Ta_TrafficPattern 本场"
	TA_SIM_EVAL CheckRideType = "Ta_SimEval 模拟机评估"
	TA_SIM CheckRideType = "Ta_Sim 模拟机检查"
	TB_SIM_EVAL CheckRideType = "Tb_SimEval 模拟机评估"
	TB_SIM CheckRideType = "Tb_Sim 模拟机检查"
)
