/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// PilotInfo - 飞行员的基本信息，包括员工号、姓名、当前行政部门和在三大队时的最后一个行政部门, 不单独使用，作为其他对象的基础
type PilotInfo struct {

	// 员工号
	StaffID string `json:"staffID,omitempty"`

	// 员工姓名
	Name string `json:"name,omitempty"`

	// 员工姓名简拼
	NameShortcut string `json:"nameShortcut,omitempty"`

	// 员工姓名拼音
	NamePinYin string `json:"namePinYin,omitempty"`

	// 当前行政部门
	CurrentDepartment string `json:"currentDepartment,omitempty"`

	// 在三大队时的最后一个行政部门
	LastDepartment3dd string `json:"lastDepartment3dd,omitempty"`

	DepartmentHistory []DepartmentHistoryRow `json:"departmentHistory,omitempty"`
}
