/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type CheckRideDetailRow struct {

	// 员工号
	StaffID string `json:"staffID,omitempty"`

	// 员工姓名
	Name string `json:"name,omitempty"`

	// 员工姓名简拼
	NameShortcut string `json:"nameShortcut,omitempty"`

	// 员工姓名拼音
	NamePinYin string `json:"namePinYin,omitempty"`

	// 当前行政部门
	CurrentDepartment string `json:"currentDepartment,omitempty"`

	// 在三大队时的最后一个行政部门
	LastDepartment3dd string `json:"lastDepartment3dd,omitempty"`

	// 行政部门历史
	DepartmentHistory []DepartmentHistoryRow `json:"departmentHistory,omitempty"`

	CheckRide CheckRideType `json:"checkRide,omitempty"`

	// 检查日期时间戳
	CheckRideDate float32 `json:"checkRideDate,omitempty"`

	CheckRideResult CheckRideResult `json:"checkRideResult,omitempty"`

	// 检查备注
	Note string `json:"note,omitempty"`
}
