/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// DepartmentHistoryRow - 飞行员在不同行政部门的历史记录，不单独使用
type DepartmentHistoryRow struct {

	// 行政部门
	Department string `json:"department,omitempty"`

	// 开始日期时间戳
	StartDate float32 `json:"startDate,omitempty"`
}
