/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type DeleteWithId struct {

	// 要删除的行的唯一id
	Id string `json:"id,omitempty"`
}
