/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type CheckRideDetailRowUpsert struct {

	// 员工号
	StaffID string `json:"staffID,omitempty"`

	CheckRide CheckRideType `json:"checkRide,omitempty"`

	// 检查日期时间戳
	CheckRideDate float32 `json:"checkRideDate,omitempty"`

	CheckRideResult CheckRideResult `json:"checkRideResult,omitempty"`

	// 检查备注
	Note string `json:"note,omitempty"`
}
