/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type AircraftType string

// List of AircraftType
const (
	B737 AircraftType = "B737"
	B777 AircraftType = "B777"
	B787 AircraftType = "B787"
	B747 AircraftType = "B747"
	_728 AircraftType = "728"
	_772 AircraftType = "772"
	_77_L AircraftType = "77L"
	_77_S AircraftType = "77S"
	_73_Q AircraftType = "73Q"
	_747 AircraftType = "747"
	_777 AircraftType = "777"
	_744 AircraftType = "744"
)
