/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type LevelOverrideRowUpsert struct {

	// 员工号
	StaffID string `json:"staffID,omitempty"`

	Level SpecificLevel `json:"level,omitempty"`

	// 要覆盖的飞行员升级日期时间戳
	LevelDate float32 `json:"levelDate,omitempty"`
}
